<?php

namespace CyberCraft\OrderMate\models;

use Illuminate\Database\Eloquent\Model;
use Bouncer;

class Customer extends Model
{
    protected $table = 'customers';
    protected $primaryKey = 'id';
    protected $fillable = ['first_name', 'last_name', 'phone', 'email', 'address'];

    public function toArray()
    {
        $array = parent::toArray(); // TODO: Change the autogenerated stub
        $array['can'] = $this->permissions();
        return $array;
    }

    /**
     * Returns the permissions of the resource.
     *
     * @return array
     */
    protected function permissions()
    {
        return [
            'browse' => Bouncer::can('browse',$this),
            'create' => Bouncer::can('create',$this),
            'read' => Bouncer::can('read', $this),
            'edit' => Bouncer::can('edit',$this),
            'delete' => Bouncer::can('delete', $this),
        ];
    }

    public function orders() {
        return $this->hasMany( Order::class );
    }
}
