<?php

namespace CyberCraft\OrderMate\models;

use Illuminate\Database\Eloquent\Model;
use Bouncer;

class Order extends Model
{
    protected $table = 'orders';
    protected $primaryKey = 'id';
    protected $fillable = ['name', 'customer_id', 'shipping_address', 'delivery_date', 'product_id', 'payment_option', 'amount', 'order_status' ];

    public function customer() {
        return $this->belongsTo( Customer::class );
    }

    public function toArray()
    {
        $array = parent::toArray(); // TODO: Change the autogenerated stub
        $array['can'] = $this->permissions();
        return $array;
    }

    /**
     * Returns the permissions of the resource.
     *
     * @return array
     */
    protected function permissions()
    {
        return [
            'browse' => Bouncer::can('browse',$this),
            'create' => Bouncer::can('create',$this),
            'read' => Bouncer::can('read', $this),
            'edit' => Bouncer::can('edit',$this),
            'delete' => Bouncer::can('delete', $this),
        ];
    }
}
